data_path: data/final/
output_path: output/aligner/
checkpoints_path: checkpoints/
max_epochs: 50
batch_size: 1
learning_rate: 1e-4
jaw: upper
weight_decay: 1e-8
scheduler_patience: 10
lambda: .8
n_samples: 10